const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.NextPrevLayout
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{GrandmasPills: 0},
	{Mouse: 0},
	{DoorButtonRight: 0},
	{DoorButtonLeft: 0},
	{RightDoor: 0},
	{DoorRight: 0},
	{LeftDoorOpen: 0},
	{DoorLeft: 0},
	{Fan: 0},
	{LightButtonRight: 0},
	{Mainmenu: 0},
	{RetryButton: 0},
	{Power: 0},
	{TimeAM: 0},
	{Uncletim: 0},
	{AuntSally: 0},
	{Golden: 0},
	{Grandma: 0},
	{sound: 0},
	{LeftDoor: 0},
	{lightsleft: 0},
	{Preview: 0},
	{keybored: 0},
	{lightsright: 0},
	{LightButtonLeft: 0},
	{ContentWarning: 0},
	{startButton: 0},
	{ventKid: 0},
	{next: 0},
	{nightOne: 0},
	{nightTwo: 0},
	{night: 0},
	{grandmawAnger: 0},
	{youDied: 0},
	{MainMenuButtonSprite: 0},
	{nextButton: 0},
	{Night3Button: 0},
	{Night2Button: 0},
	{Night1Button: 0},
	{MainMenuButton: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{PlzWork: 0},
	{oop: 0},
	{contiue: 0},
	{TiledBackground3: 0},
	{GrandmawAnger: 0},
	{Lives: 0},
	{TimeAm: 0},
	{Power2: 0},
	{GrandmawAnger2: 0},
	{Lives2: 0},
	{TimeAm2: 0},
	{Power3: 0},
	{GrandmawAnger3: 0},
	{Lives3: 0},
	{TimeAm3: 0}
];

self.InstanceType = {
	Background: class extends self.ITiledBackgroundInstance {},
	GrandmasPills: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	DoorButtonRight: class extends self.ISpriteInstance {},
	DoorButtonLeft: class extends self.ISpriteInstance {},
	DoorRight: class extends self.ISpriteInstance {},
	DoorLeft: class extends self.ISpriteInstance {},
	Fan: class extends self.ISpriteInstance {},
	LightButtonRight: class extends self.ISpriteInstance {},
	Mainmenu: class extends self.ISpriteInstance {},
	RetryButton: class extends self.ISpriteInstance {},
	Power: class extends self.ITextInstance {},
	TimeAM: class extends self.ITextInstance {},
	Uncletim: class extends self.ISpriteInstance {},
	AuntSally: class extends self.ISpriteInstance {},
	Golden: class extends self.ISpriteInstance {},
	Grandma: class extends self.ISpriteInstance {},
	sound: class extends self.IInstance {},
	RightDoor: class extends self.ISpriteInstance {},
	LeftDoor: class extends self.ISpriteInstance {},
	lightsleft: class extends self.ISpriteInstance {},
	Preview: class extends self.ISpriteInstance {},
	keybored: class extends self.IInstance {},
	lightsright: class extends self.ISpriteInstance {},
	LightButtonLeft: class extends self.ISpriteInstance {},
	ContentWarning: class extends self.ITiledBackgroundInstance {},
	startButton: class extends self.ISpriteInstance {},
	ventKid: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	nightOne: class extends self.ISpriteInstance {},
	nightTwo: class extends self.ISpriteInstance {},
	night: class extends self.ISpriteInstance {},
	grandmawAnger: class extends self.ITextInstance {},
	youDied: class extends self.ITiledBackgroundInstance {},
	MainMenuButtonSprite: class extends self.ISpriteInstance {},
	nextButton: class extends self.IButtonInstance {},
	Night3Button: class extends self.IButtonInstance {},
	Night2Button: class extends self.IButtonInstance {},
	Night1Button: class extends self.IButtonInstance {},
	MainMenuButton: class extends self.IButtonInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	PlzWork: class extends self.IButtonInstance {},
	oop: class extends self.ISpriteInstance {},
	contiue: class extends self.IButtonInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {}
}